### ISSUE TITLE
Restrict light/dark using the iterm scheme information

### ISSUE THREAD

**Issue by clnoll** [dandavison/iterm2-color-scheme#8]
Currently the schemes are restricted to light/dark in a hardcoded list.  Would be great to determine light/dark using the data in the scheme itself.

**Comment by dandavison** [comment]
It seems that the python standard library has a module [colorsys](https://docs.python.org/2/library/colorsys.html) which would make it easy to convert the RGB values to  [other schemes](https://en.wikipedia.org/wiki/HSL_and_HSV). Then maybe the "lightness" value of the HSL scheme is the right thing to use.

**Comment by dandavison** [comment]
Fixed by https://github.com/dandavison/iterminator/pull/9
